### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no netty_tcnative_windows_x86_64 in java.library.path

### ISSUE THREAD

**Issue by bjcawanglu** [FISCO-BCOS/java-sdk#306]
java.lang.UnsatisfiedLinkError: no netty_tcnative_windows_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:385)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:377)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:592)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:136)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:196)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:185)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:34)
	at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:189)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:827)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:576)
	at org.fisco.bcos.sdk.network.ConnectionManager.initSslContext(ConnectionManager.java:251)
	at org.fisco.bcos.sdk.network.ConnectionManager.initNetty(ConnectionManager.java:330)
	at org.fisco.bcos.sdk.network.ConnectionManager.startConnect(ConnectionManager.java:103)
	at org.fisco.bcos.sdk.network.NetworkImp.start(NetworkImp.java:160)
	at org.fisco.bcos.sdk.channel.ChannelImp.start(ChannelImp.java:89)
	at org.fisco.bcos.sdk.BcosSDK.<init>(BcosSDK.java:75)

**Comment by cyjseagull** [comment]
> java.lang.UnsatisfiedLinkError: no netty_tcnative_windows_x86_64 in java.library.path
> at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
> at java.lang.Runtime.loadLibrary0(Runtime.java:870)
> at java.lang.System.loadLibrary(System.java:1122)
> at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:385)
> at java.security.AccessController.doPrivileged(Native Method)
> at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:377)
> at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
> at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
> at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
> at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:592)
> at io.netty.handler.ssl.OpenSsl.(OpenSsl.java:136)
> at io.netty.handler.ssl.ReferenceCountedOpenSslContext.(ReferenceCountedOpenSslContext.java:196)
> at io.netty.handler.ssl.ReferenceCountedOpenSslContext.(ReferenceCountedOpenSslContext.java:185)
> at io.netty.handler.ssl.OpenSslContext.(OpenSslContext.java:34)
> at io.netty.handler.ssl.OpenSslClientContext.(OpenSslClientContext.java:189)
> at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:827)
> at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:576)
> at org.fisco.bcos.sdk.network.ConnectionManager.initSslContext(ConnectionManager.java:251)
> at org.fisco.bcos.sdk.network.ConnectionManager.initNetty(ConnectionManager.java:330)
> at org.fisco.bcos.sdk.network.ConnectionManager.startConnect(ConnectionManager.java:103)
> at org.fisco.bcos.sdk.network.NetworkImp.start(NetworkImp.java:160)
> at org.fisco.bcos.sdk.channel.ChannelImp.start(ChannelImp.java:89)
> at org.fisco.bcos.sdk.BcosSDK.(BcosSDK.java:75)


java-sdk是哪个版本的，有没有同时使用web3sdk呢
