### ISSUE TITLE
fisco-bcos-java-sdk:v2.8.0无法连接到链节点

### ISSUE THREAD

**Issue by NiuwenC** [FISCO-BCOS/java-sdk#414]
如下代码:
`BcosSDK sdk = BcosSDK.build(path);`
版本 2.7.2成功
版本2.8.0 失败，如下错误:
`
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.webank.wedpr.crypto.NativeInterface.secp256k1GenKeyPair()Lcom/webank/wedpr/crypto/CryptoResult;
	at com.webank.wedpr.crypto.NativeInterface.secp256k1GenKeyPair(Native Method)
	at org.fisco.bcos.sdk.crypto.keypair.ECDSAKeyPair.generateKeyPair(ECDSAKeyPair.java:66)
	at org.fisco.bcos.sdk.crypto.keypair.ECDSAKeyPair.<init>(ECDSAKeyPair.java:31)
	at org.fisco.bcos.sdk.crypto.CryptoSuite.initCryptoSuite(CryptoSuite.java:112)
	at org.fisco.bcos.sdk.crypto.CryptoSuite.<init>(CryptoSuite.java:100)
	at org.fisco.bcos.sdk.amop.AmopImp.<init>(AmopImp.java:55)
	at org.fisco.bcos.sdk.amop.Amop.build(Amop.java:40)
	at org.fisco.bcos.sdk.BcosSDK.<init>(BcosSDK.java:100)
	at org.fisco.bcos.sdk.BcosSDK.build(BcosSDK.java:59)
	at com.jackniu.fisco.BcosSDKTest.main(BcosSDKTest.java:20)

`

**Comment by cyjseagull** [comment]
可以清楚本地的gradlew/mvn缓存后，重新下载、替换2.8.0试试。
